name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_RELEASE: matmaul/cnpg-postgresql

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-20.04
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Generate Jobs
        id: generate-jobs
        shell: bash
        run: |
          bash .github/generate-strategy.sh

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.0.0
      with:
        image: tonistiigi/binfmt:qemu-v6.1.0
        platforms: ${{ steps.docker-platforms.outputs.platforms }}

    - name: Docker meta
      id: docker-meta
      env:
        TAGS: ${{ toJson(matrix.tags) }}
      run: |
        RESULT=""
        for tag in $(jq -r '.[]' <<< "${TAGS}")
        do
          RESULT="${RESULT},ghcr.io/${IMAGE_RELEASE}:${tag}"
        done
        echo "::set-output name=tags::${RESULT%,}"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        context: ${{ matrix.dir }}
        file: ${{ matrix.file }}
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
